### ISSUE TITLE
UI tweaks

### ISSUE THREAD

**Issue by thomascobb** [epics-containers/vscode-ibek-entities#4]
- [x] Add incrementing value option drag and fill (could do as a right click option on highlighted cells, or detect an increment like excel, try drag fill in excel for 1 cell, then 2 cells with different values in them)
- [x] Make a single undo/redo stack for the page that hooks into the undo and redo vs code actions
- [x] Make the vs code save action trigger save
- [x] Make sure comments are persisted for rows that are edited but not deleted
- [x] Try our best to write tables back to YAML, even if they have missing columns or contain invalid data
- [x] Allow split tables, i.e. `[Geobrick1, Motor1, Motor2, Motor3, Geobrick2, Motor4, Motor5]` should make 4 tables, not 2
- [x] Remove `Resize table, hide comments/help, fixed rows from top, reload from saved, read only mode, add column, apply changes`
- [x] Rename "edit yaml" button - add keyboard shortcut?
- [ ] Change "Add row" triple button to "Add row above, Add row below, Delete row" buttons with symbols like confluence tables have

**Comment by abigailalexander** [comment]
I've implemented the [YAML parser ](https://eemeli.org/yaml/v1/#yaml) that vscode-yaml uses (that uses an AST) and that now makes it possible to preserve comments provided that the row underneath the comment isn't deleted, and changes in the table/file are written between each other even if the data isn't valid against the schema (this could cause some issues in displaying the table if the data is in the wrong format, however).

**Comment by abigailalexander** [comment]
I was able to hook into the undo/redo VSCode buttons and implement a global undo/redo stack, although currently it only includes changes to cells and not adding/deleting/moving rows, but that should be possible to add in. Actions like adding and deleting tables are also not included in the global undo/redo stack at the moment, and including them might be a lot harder since I won't be able to utilise handsontable's own undo handling to do most of the actual work. Hooking into VSCode's "save" button has also been implemented, and keyboard shortcuts for all of these work from the extension webview.
